sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t bcjuan/docker-react-course -f Dockerfile.dev . 

script:
  - docker run -e CI=true bcjuan/docker-react-course npm run test